/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Animacion.Fade;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import servicios.Registros;

/**
 *
 * @author edwin
 */
public class AgregarEvento extends javax.swing.JDialog {

    private int x,y;
    private Registros reg;
    private Map datos;
    
    
    public AgregarEvento(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
        JSpinner.DateEditor timeEditor = new JSpinner.DateEditor(this.horaS, "HH:mm");
        JSpinner.DateEditor timeEditor2 = new JSpinner.DateEditor(this.horaF, "HH:mm");
        
        this.horaS.setEditor(timeEditor);
        this.horaF.setEditor(timeEditor2);
        reg = new Registros();
        
        datos = new HashMap();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        horaS = new javax.swing.JSpinner();
        horaF = new javax.swing.JSpinner();
        lugar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        categoria = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        SiRepetir = new javax.swing.JRadioButton();
        NoRepetir = new javax.swing.JRadioButton();
        Repetir = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(12, 12, 22));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/addPequeño.png"))); // NOI18N
        jLabel2.setText("AGREGAR UN EVENTO");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, 940, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 40));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TITULO:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        titulo.setBackground(new java.awt.Color(12, 12, 22));
        titulo.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setToolTipText("Nombre del evento");
        titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        titulo.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 250, 20));

        fecha.setBackground(new java.awt.Color(0, 0, 0));
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setToolTipText("Fecha de realizacion del evento");
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 250, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FECHA:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("HORA:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        horaS.setModel(new SpinnerDateModel());
        horaS.setToolTipText("Hora inicio de evento");
        horaS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 2));
        jPanel1.add(horaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 110, 30));

        horaF.setModel(new SpinnerDateModel());
        horaF.setToolTipText("Hora fin de evento");
        horaF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        jPanel1.add(horaF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 110, 30));

        lugar.setBackground(new java.awt.Color(12, 12, 22));
        lugar.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        lugar.setForeground(new java.awt.Color(255, 255, 255));
        lugar.setToolTipText("Nombre del evento");
        lugar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lugar.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 250, 20));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("LUGAR:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CATEGORIA:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, -1));

        categoria.setBackground(new java.awt.Color(0, 0, 0));
        categoria.setForeground(new java.awt.Color(255, 255, 255));
        categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cumpleaños", "Citas Médicas", "Reuniones", "Bodas", "Otros" }));
        categoria.setToolTipText("Categoria del evento");
        jPanel1.add(categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 250, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("REPETIR:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        SiRepetir.setBackground(new java.awt.Color(12, 12, 22));
        buttonGroup1.add(SiRepetir);
        SiRepetir.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        SiRepetir.setForeground(new java.awt.Color(255, 255, 255));
        SiRepetir.setSelected(true);
        SiRepetir.setText("SI");
        SiRepetir.setFocusPainted(false);
        SiRepetir.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SiRepetirStateChanged(evt);
            }
        });
        jPanel1.add(SiRepetir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, -1, -1));

        NoRepetir.setBackground(new java.awt.Color(12, 12, 22));
        buttonGroup1.add(NoRepetir);
        NoRepetir.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        NoRepetir.setForeground(new java.awt.Color(255, 255, 255));
        NoRepetir.setText("NO");
        NoRepetir.setFocusPainted(false);
        NoRepetir.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                NoRepetirStateChanged(evt);
            }
        });
        jPanel1.add(NoRepetir, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, -1, -1));

        Repetir.setBackground(new java.awt.Color(12, 12, 22));
        Repetir.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Repetir.setForeground(new java.awt.Color(255, 255, 255));
        Repetir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diariamente", "Semanalmente", "Mensualmente", "Anualmente" }));
        Repetir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Repetir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Repetir, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 120, -1));

        descripcion.setBackground(new java.awt.Color(12, 12, 22));
        descripcion.setColumns(20);
        descripcion.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        descripcion.setForeground(new java.awt.Color(255, 255, 255));
        descripcion.setLineWrap(true);
        descripcion.setRows(5);
        descripcion.setToolTipText("Agregue una descripcion del evento");
        descripcion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(descripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 248, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DESCRIPCION:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        Guardar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/save.png"))); // NOI18N
        Guardar.setText("GUARDAR");
        Guardar.setToolTipText("Guardar mis datos");
        Guardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        Guardar.setBorderPainted(false);
        Guardar.setContentAreaFilled(false);
        Guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Guardar.setFocusPainted(false);
        Guardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/savePq.png"))); // NOI18N
        Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GuardarMouseExited(evt);
            }
        });
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 120, 30));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MI NUEVO EVENTO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 950, 30));

        btnCerrar.setBackground(new java.awt.Color(102, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/close.png"))); // NOI18N
        btnCerrar.setText("CERRAR");
        btnCerrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setFocusPainted(false);
        btnCerrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/closePeque.png"))); // NOI18N
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarMouseExited(evt);
            }
        });
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX()- x , this.getLocation().y + evt.getY() - y );
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void SiRepetirStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SiRepetirStateChanged
        if(this.SiRepetir.isSelected()){
            this.Repetir.setEnabled(true);
        }
    }//GEN-LAST:event_SiRepetirStateChanged

    private void NoRepetirStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_NoRepetirStateChanged
       if(this.NoRepetir.isSelected()){
            this.Repetir.setEnabled(false);
       }
    }//GEN-LAST:event_NoRepetirStateChanged

    private void GuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarMouseEntered
        this.Guardar.setBorderPainted(true);
    }//GEN-LAST:event_GuardarMouseEntered

    private void GuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarMouseExited
        this.Guardar.setBorderPainted(false);
    }//GEN-LAST:event_GuardarMouseExited

    private void btnCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseEntered
        this.btnCerrar.setBorderPainted(true);
    }//GEN-LAST:event_btnCerrarMouseEntered

    private void btnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseExited
        this.btnCerrar.setBorderPainted(false);
    }//GEN-LAST:event_btnCerrarMouseExited

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        Fade.JDialogFadeOut(1f, 0f, 0.1f, 50, this,Fade.DISPOSE);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
       
        if(!this.titulo.getText().isEmpty() && !this.descripcion.getText().isEmpty() &&
                !this.lugar.getText().isEmpty()){
            int mes = this.fecha.getCalendar().get(Calendar.MONTH)+1;
            int dia = this.fecha.getCalendar().get(Calendar.DAY_OF_MONTH);
            int anio = this.fecha.getCalendar().get(Calendar.YEAR);
            DateFormat hourFormat = new SimpleDateFormat("HH:mm");
            String repeticion;

            datos.put("titulo", this.titulo.getText());
            datos.put("descripcion", this.descripcion.getText());
            datos.put("fecha", String.valueOf(dia)+"/"+String.valueOf(mes)+"/"+String.valueOf(anio));
            datos.put("hora", hourFormat.format(this.horaS.getValue()));

            datos.put("categoria", this.categoria.getSelectedItem());

            if(this.SiRepetir.isSelected()){
                datos.put("repetir", "SI");
                repeticion = this.Repetir.getSelectedItem().toString();
            }else{
                 datos.put("repetir", "NO");
                repeticion = "NULL";
            }

            datos.put("dia", String.valueOf(dia));
            datos.put("mes", String.valueOf(mes-1));
            datos.put("horaFin", hourFormat.format(this.horaF.getValue()));
            datos.put("anio", String.valueOf(anio));
            datos.put("diaLetras", this.fecha.getCalendar().get(Calendar.DAY_OF_WEEK));
            datos.put("mesLetras", mes-1);
            datos.put("repeticion", repeticion);
            datos.put("lugar", this.lugar.getText());
            datos.put("diaSemana", this.fecha.getCalendar().get(Calendar.DAY_OF_WEEK));

            reg.crearEvento(datos);

            JOptionPane.showMessageDialog(null, "Evento creado Correctamente");

            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No puede dejar campos vacíos");
        }
    }//GEN-LAST:event_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarEvento dialog = new AgregarEvento(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JRadioButton NoRepetir;
    private javax.swing.JComboBox<String> Repetir;
    private javax.swing.JRadioButton SiRepetir;
    private javax.swing.JButton btnCerrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> categoria;
    private javax.swing.JTextArea descripcion;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JSpinner horaF;
    private javax.swing.JSpinner horaS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lugar;
    private javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables
}
