/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.io.File;
import java.io.IOException;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import servicios.Fuente;

/**
 *
 * @author josuee
 */
public class Cronometro extends javax.swing.JFrame {

    public int getHours() {
        return Hours;
    }

    public void setHours(int Hours) {
        this.Hours = Hours;
    }

    public int getMinutes() {
        return Minutes;
    }

    public void setMinutes(int Minutes) {
        this.Minutes = Minutes;
    }

    public int getSeconds() {
        return Seconds;
    }

    public void setSeconds(int Seconds) {
        this.Seconds = Seconds;
    }

    public int getMiliSeconds() {
        return MiliSeconds;
    }

    public void setMiliSeconds(int MiliSeconds) {
        this.MiliSeconds = MiliSeconds;
    }

    /**
     * Creates new form Cronometro
     */
    
    private Timer timer;
    private int Hours;
    private int Minutes;
    private int Seconds;
    private int MiliSeconds;
    private boolean init;
    Clip sonido;
    
    public Cronometro(){
            initComponents();
            setHours(0);
            setMinutes(0);
            setSeconds(0);
            setMiliSeconds(0);
            Fuente fuente = new Fuente("tenoclock");
            this.LblHours.setFont(fuente.MiFont(0, 48));
            this.LblMiliSeconds.setFont(fuente.MiFont(0, 48));
            this.LblMinutes.setFont(fuente.MiFont(0, 48));
            this.LblSeconds.setFont(fuente.MiFont(0, 48));
            
            this.jLabel2.setFont(fuente.MiFont(0, 48));
            this.jLabel4.setFont(fuente.MiFont(0, 48));
            this.jLabel6.setFont(fuente.MiFont(0, 48));
            
            init = false;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        LblHours = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LblMinutes = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LblSeconds = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LblMiliSeconds = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BtnIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        LblHours.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        LblHours.setText("00");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2.setText(":");

        LblMinutes.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        LblMinutes.setText("00");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel4.setText(":");

        LblSeconds.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        LblSeconds.setText("00");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel6.setText(":");

        LblMiliSeconds.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        LblMiliSeconds.setText("000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(LblHours)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblMinutes)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblSeconds)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblMiliSeconds)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblHours)
                    .addComponent(jLabel2)
                    .addComponent(LblMinutes)
                    .addComponent(jLabel4)
                    .addComponent(LblSeconds)
                    .addComponent(jLabel6)
                    .addComponent(LblMiliSeconds))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        BtnIniciar.setText("Iniciar");
        BtnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnIniciar)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(BtnIniciar)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIniciarActionPerformed
        if(init == false){
            setHours(0);
            setMinutes(0);
            setSeconds(0);
            setMiliSeconds(0);
            timer = new Timer();
            iniciarCronometro();
            this.BtnIniciar.setText("Pausar");
            init = true;
        }else{
            getTimer().cancel();
            init = false;
            this.BtnIniciar.setText("Iniciar");
        }
    }//GEN-LAST:event_BtnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cronometro().setVisible(true);
            }
        });
    }
    
    public void iniciarCronometro(){
             // Clase en la que está el código a ejecutar 
     TimerTask timerTask = new TimerTask() { 
         public void run()  {
             
             /*if(getSeconds() == 15){
                 timer.cancel();
                 init = false;
                 BtnIniciar.setText("Iniciar");
                 
             }*/
             
             setMiliSeconds(getMiliSeconds()+1);
             if(getMiliSeconds() == 1000){
                 setMiliSeconds(0);
                 setSeconds(getSeconds()+1);

                 if(getSeconds() == 60){
                     setSeconds(0);
                     setMinutes(getMinutes()+1);
                     
                     if(getMinutes() == 60){
                         setMinutes(0);
                         setHours(getHours()+1);
                     }
                     
                 }
             }
             
             actualizarVentana(String.valueOf(getHours()), String.valueOf(getMinutes()), 
                     String.valueOf(getSeconds()),String.valueOf(getMiliSeconds()));
             
         } 
     };
     
     
     // Dentro de 0 milisegundos avísame cada 1000 milisegundos 
        getTimer().scheduleAtFixedRate(timerTask, 0, 1);

    }
    
    public void actualizarVentana(String horas, String minutos, String segundos, String mili){
        
        if(horas.length() == 1){
            horas = "0"+horas;
        }
        
        if(minutos.length() == 1){
            minutos = "0"+minutos;
        }
        
        if(segundos.length() == 1){
            segundos = "0"+segundos;
        }
        
        if(mili.length() == 1){
            mili = "00"+mili;
        }
        
        if(mili.length() == 2){
            mili = "0"+mili;
        }
        

        LblMiliSeconds.setText(mili);
        LblSeconds.setText(segundos);
        LblMinutes.setText(minutos);
        LblHours.setText(horas);
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIniciar;
    private javax.swing.JLabel LblHours;
    private javax.swing.JLabel LblMiliSeconds;
    private javax.swing.JLabel LblMinutes;
    private javax.swing.JLabel LblSeconds;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    public Timer getTimer() {
        return timer;
    }

    public void setTimer(Timer timer) {
        this.timer = timer;
    }
}
