/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;
import servicios.Registros;

/**
 *
 * @author c3rberuss
 */
public class Eventos extends javax.swing.JDialog implements ActionListener{

    /**
     * Creates new form Eventos
     */
    
    private Registros reg;
    private Map componentes;
    private DetalleEvento detalle;
    
    public Eventos(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);

        agregarTarjetas();
        componentes = new HashMap();
        reg = new Registros();
        
     /*   if(reg.cargarCumpleanios(this.eventosCumple, this.componentes, this) < 1){
            this.jTabbedPane1.remove(this.Cumpleanios);
        }
        
        if(reg.cargarCitas(eventosCitas, componentes, this) < 1){
            this.jTabbedPane1.remove(this.CitasMedicas);
        }
        
        if(reg.cargarReuniones(eventosReuniones, componentes, this) < 1){
            this.jTabbedPane1.remove(this.Reuniones);
        }
        
        if(reg.cargarBodas(eventosBodas, componentes, this) < 1){
            this.jTabbedPane1.remove(this.Bodas);
        }
        
        if(reg.cargarOtros(eventosOtros, componentes, this) < 1){
            this.jTabbedPane1.remove(this.Otros);
        }*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Cumpleanios = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventosCumple = new javax.swing.JPanel();
        CitasMedicas = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        eventosCitas = new javax.swing.JPanel();
        Reuniones = new javax.swing.JInternalFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        eventosReuniones = new javax.swing.JPanel();
        Bodas = new javax.swing.JInternalFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        eventosBodas = new javax.swing.JPanel();
        Otros = new javax.swing.JInternalFrame();
        jScrollPane5 = new javax.swing.JScrollPane();
        eventosOtros = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(12, 12, 22));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        Cumpleanios.setBackground(new java.awt.Color(0, 0, 0));
        Cumpleanios.setBorder(null);
        Cumpleanios.setForeground(new java.awt.Color(0, 0, 0));
        Cumpleanios.setVisible(true);

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        eventosCumple.setBackground(new java.awt.Color(0, 0, 0));
        eventosCumple.setForeground(new java.awt.Color(255, 255, 255));
        eventosCumple.setLayout(new java.awt.GridLayout(0, 2, 10, 15));
        jScrollPane1.setViewportView(eventosCumple);

        javax.swing.GroupLayout CumpleaniosLayout = new javax.swing.GroupLayout(Cumpleanios.getContentPane());
        Cumpleanios.getContentPane().setLayout(CumpleaniosLayout);
        CumpleaniosLayout.setHorizontalGroup(
            CumpleaniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
        );
        CumpleaniosLayout.setVerticalGroup(
            CumpleaniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Cumpleaños", Cumpleanios);

        CitasMedicas.setBackground(new java.awt.Color(0, 0, 0));
        CitasMedicas.setBorder(null);
        CitasMedicas.setForeground(new java.awt.Color(0, 0, 0));
        CitasMedicas.setVisible(true);

        jScrollPane2.setBorder(null);

        eventosCitas.setBackground(new java.awt.Color(0, 0, 0));
        eventosCitas.setForeground(new java.awt.Color(255, 255, 255));
        eventosCitas.setLayout(new java.awt.GridLayout(0, 2, 10, 15));
        jScrollPane2.setViewportView(eventosCitas);

        javax.swing.GroupLayout CitasMedicasLayout = new javax.swing.GroupLayout(CitasMedicas.getContentPane());
        CitasMedicas.getContentPane().setLayout(CitasMedicasLayout);
        CitasMedicasLayout.setHorizontalGroup(
            CitasMedicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        CitasMedicasLayout.setVerticalGroup(
            CitasMedicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        jTabbedPane1.addTab("Citas Médicas", CitasMedicas);

        Reuniones.setBackground(new java.awt.Color(0, 0, 0));
        Reuniones.setBorder(null);
        Reuniones.setForeground(new java.awt.Color(0, 0, 0));
        Reuniones.setVisible(true);

        jScrollPane3.setBorder(null);

        eventosReuniones.setBackground(new java.awt.Color(0, 0, 0));
        eventosReuniones.setForeground(new java.awt.Color(255, 255, 255));
        eventosReuniones.setLayout(new java.awt.GridLayout(0, 2, 10, 15));
        jScrollPane3.setViewportView(eventosReuniones);

        javax.swing.GroupLayout ReunionesLayout = new javax.swing.GroupLayout(Reuniones.getContentPane());
        Reuniones.getContentPane().setLayout(ReunionesLayout);
        ReunionesLayout.setHorizontalGroup(
            ReunionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        ReunionesLayout.setVerticalGroup(
            ReunionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );

        jTabbedPane1.addTab("Reuniones", Reuniones);

        Bodas.setBackground(new java.awt.Color(0, 0, 0));
        Bodas.setBorder(null);
        Bodas.setForeground(new java.awt.Color(0, 0, 0));
        Bodas.setVisible(true);

        jScrollPane4.setBorder(null);

        eventosBodas.setBackground(new java.awt.Color(0, 0, 0));
        eventosBodas.setForeground(new java.awt.Color(255, 255, 255));
        eventosBodas.setLayout(new java.awt.GridLayout(0, 2, 10, 15));
        jScrollPane4.setViewportView(eventosBodas);

        javax.swing.GroupLayout BodasLayout = new javax.swing.GroupLayout(Bodas.getContentPane());
        Bodas.getContentPane().setLayout(BodasLayout);
        BodasLayout.setHorizontalGroup(
            BodasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );
        BodasLayout.setVerticalGroup(
            BodasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );

        jTabbedPane1.addTab("Bodas", Bodas);

        Otros.setBackground(new java.awt.Color(0, 0, 0));
        Otros.setBorder(null);
        Otros.setForeground(new java.awt.Color(0, 0, 0));
        Otros.setVisible(true);

        jScrollPane5.setBorder(null);

        eventosOtros.setBackground(new java.awt.Color(0, 0, 0));
        eventosOtros.setForeground(new java.awt.Color(255, 255, 255));
        eventosOtros.setLayout(new java.awt.GridLayout(0, 2, 10, 15));
        jScrollPane5.setViewportView(eventosOtros);

        javax.swing.GroupLayout OtrosLayout = new javax.swing.GroupLayout(Otros.getContentPane());
        Otros.getContentPane().setLayout(OtrosLayout);
        OtrosLayout.setHorizontalGroup(
            OtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
        );
        OtrosLayout.setVerticalGroup(
            OtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
        );

        jTabbedPane1.addTab("Otros", Otros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Eventos dialog = new Eventos(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void agregarTarjetas(){
        for(int i = 0; i < 19; i++){
            TarjetaEvento tarjeta = new TarjetaEvento();
            tarjeta.Fecha.setText("Jueves 05");
            tarjeta.Mes.setText("NOV");
            tarjeta.titulo.setText("Cumpleaños de tu gfa");
            this.eventosCumple.add(tarjeta);
            this.eventosCumple.updateUI();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame Bodas;
    private javax.swing.JInternalFrame CitasMedicas;
    private javax.swing.JInternalFrame Cumpleanios;
    private javax.swing.JInternalFrame Otros;
    private javax.swing.JInternalFrame Reuniones;
    private javax.swing.JPanel eventosBodas;
    private javax.swing.JPanel eventosCitas;
    private javax.swing.JPanel eventosCumple;
    private javax.swing.JPanel eventosOtros;
    private javax.swing.JPanel eventosReuniones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        //se obtiene el comando ejecutado
        String comando = e.getActionCommand();
        //se recorre el MAP
        Iterator it = componentes.entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry entry = (Map.Entry)it.next();
            //se obtiene el KEY -> identificador unico
            String itm = entry.getKey().toString();
            //si comando de componente es igual a comando pulsado
            if( itm.equals(comando))
            {
                //se recupera el contenido del JTextfield
                //String name = ((jpComponente) entry.getValue()).txtName.getText();
                //mostramos resultado
                //JOptionPane.showMessageDialog(null, "Se presiono boton " + itm + " \n Hola " );//+ name);
                
                detalle = new DetalleEvento(null, true, comando);
                detalle.setLocationRelativeTo(null);
                detalle.setVisible(true);
                
            }
        }
    }
}
