/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Animacion.Fade;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import servicios.Registros;

/**
 *
 * @author edwin
 */
public class MostrarEventos extends javax.swing.JDialog implements ActionListener{

    /**
     * Creates new form Eventos
     */
    
    private Registros reg;
    private Map componentes;
    private DetalleEvento detalle;
    
    public MostrarEventos(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
        componentes = new HashMap();
        reg = new Registros();
        
        if(reg.cargarCumpleanios(this.eventosCumple, this.componentes, this) < 1){
            this.jTabbedPane1.remove(this.Cumpleanios);
        }
        
        if(reg.cargarCitas(eventosCitas, componentes, this) < 1){
            this.jTabbedPane1.remove(this.CitasMedicas);
        }
        
        if(reg.cargarReuniones(eventosReuniones, componentes, this) < 1){
            this.jTabbedPane1.remove(this.Reuniones);
        }
        
        if(reg.cargarBodas(eventosBodas, componentes, this) < 1){
            this.jTabbedPane1.remove(this.Bodas);
        }
        
        if(reg.cargarOtros(eventosOtros, componentes, this) < 1){
            this.jTabbedPane1.remove(this.Otros);
        }
     
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Cumpleanios = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventosCumple = new javax.swing.JPanel();
        CitasMedicas = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        eventosCitas = new javax.swing.JPanel();
        Reuniones = new javax.swing.JInternalFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        eventosReuniones = new javax.swing.JPanel();
        Bodas = new javax.swing.JInternalFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        eventosBodas = new javax.swing.JPanel();
        Otros = new javax.swing.JInternalFrame();
        jScrollPane5 = new javax.swing.JScrollPane();
        eventosOtros = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(12, 12, 22));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/eventoLogoTitulo.png"))); // NOI18N
        jLabel2.setText("MIS EVENTOS");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, 940, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 40));

        btnCerrar.setBackground(new java.awt.Color(102, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("CERRAR");
        btnCerrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setFocusPainted(false);
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarMouseExited(evt);
            }
        });
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, 80, 30));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        Cumpleanios.setBackground(new java.awt.Color(12, 12, 22));
        Cumpleanios.setBorder(null);
        Cumpleanios.setForeground(new java.awt.Color(0, 0, 0));
        Cumpleanios.setVisible(true);

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        eventosCumple.setBackground(new java.awt.Color(12, 12, 22));
        eventosCumple.setForeground(new java.awt.Color(255, 255, 255));
        java.awt.GridBagLayout eventosCumpleLayout = new java.awt.GridBagLayout();
        eventosCumpleLayout.columnWidths = new int[] {420};
        eventosCumpleLayout.rowHeights = new int[] {100};
        eventosCumpleLayout.columnWeights = new double[] {1.0};
        eventosCumpleLayout.rowWeights = new double[] {1.0};
        eventosCumple.setLayout(eventosCumpleLayout);
        jScrollPane1.setViewportView(eventosCumple);

        javax.swing.GroupLayout CumpleaniosLayout = new javax.swing.GroupLayout(Cumpleanios.getContentPane());
        Cumpleanios.getContentPane().setLayout(CumpleaniosLayout);
        CumpleaniosLayout.setHorizontalGroup(
            CumpleaniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
        );
        CumpleaniosLayout.setVerticalGroup(
            CumpleaniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Cumpleaños", Cumpleanios);

        CitasMedicas.setBackground(new java.awt.Color(12, 12, 22));
        CitasMedicas.setBorder(null);
        CitasMedicas.setForeground(new java.awt.Color(0, 0, 0));
        CitasMedicas.setVisible(true);

        jScrollPane2.setBorder(null);

        eventosCitas.setBackground(new java.awt.Color(12, 12, 22));
        eventosCitas.setForeground(new java.awt.Color(255, 255, 255));
        eventosCitas.setLayout(new java.awt.GridBagLayout());
        jScrollPane2.setViewportView(eventosCitas);

        javax.swing.GroupLayout CitasMedicasLayout = new javax.swing.GroupLayout(CitasMedicas.getContentPane());
        CitasMedicas.getContentPane().setLayout(CitasMedicasLayout);
        CitasMedicasLayout.setHorizontalGroup(
            CitasMedicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CitasMedicasLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CitasMedicasLayout.setVerticalGroup(
            CitasMedicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CitasMedicasLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Citas Médicas", CitasMedicas);

        Reuniones.setBackground(new java.awt.Color(12, 12, 22));
        Reuniones.setBorder(null);
        Reuniones.setForeground(new java.awt.Color(0, 0, 0));
        Reuniones.setVisible(true);

        jScrollPane3.setBorder(null);

        eventosReuniones.setBackground(new java.awt.Color(12, 12, 22));
        eventosReuniones.setForeground(new java.awt.Color(255, 255, 255));
        eventosReuniones.setLayout(new java.awt.GridBagLayout());
        jScrollPane3.setViewportView(eventosReuniones);

        javax.swing.GroupLayout ReunionesLayout = new javax.swing.GroupLayout(Reuniones.getContentPane());
        Reuniones.getContentPane().setLayout(ReunionesLayout);
        ReunionesLayout.setHorizontalGroup(
            ReunionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
        );
        ReunionesLayout.setVerticalGroup(
            ReunionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Reuniones", Reuniones);

        Bodas.setBackground(new java.awt.Color(12, 12, 22));
        Bodas.setBorder(null);
        Bodas.setForeground(new java.awt.Color(0, 0, 0));
        Bodas.setVisible(true);

        jScrollPane4.setBorder(null);

        eventosBodas.setBackground(new java.awt.Color(12, 12, 22));
        eventosBodas.setForeground(new java.awt.Color(255, 255, 255));
        eventosBodas.setLayout(new java.awt.GridBagLayout());
        jScrollPane4.setViewportView(eventosBodas);

        javax.swing.GroupLayout BodasLayout = new javax.swing.GroupLayout(Bodas.getContentPane());
        Bodas.getContentPane().setLayout(BodasLayout);
        BodasLayout.setHorizontalGroup(
            BodasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
        );
        BodasLayout.setVerticalGroup(
            BodasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Bodas", Bodas);

        Otros.setBackground(new java.awt.Color(12, 12, 22));
        Otros.setBorder(null);
        Otros.setForeground(new java.awt.Color(0, 0, 0));
        Otros.setVisible(true);

        jScrollPane5.setBorder(null);

        eventosOtros.setBackground(new java.awt.Color(12, 12, 22));
        eventosOtros.setForeground(new java.awt.Color(255, 255, 255));
        eventosOtros.setLayout(new java.awt.GridBagLayout());
        jScrollPane5.setViewportView(eventosOtros);

        javax.swing.GroupLayout OtrosLayout = new javax.swing.GroupLayout(Otros.getContentPane());
        Otros.getContentPane().setLayout(OtrosLayout);
        OtrosLayout.setHorizontalGroup(
            OtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
        );
        OtrosLayout.setVerticalGroup(
            OtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Otros", Otros);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, 930, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseEntered
        this.btnCerrar.setBorderPainted(true);
    }//GEN-LAST:event_btnCerrarMouseEntered

    private void btnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseExited
        this.btnCerrar.setBorderPainted(false);
    }//GEN-LAST:event_btnCerrarMouseExited

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        Fade.JDialogFadeOut(1f, 0f, 0.1f, 50, this,Fade.DISPOSE);
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MostrarEventos dialog = new MostrarEventos(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame Bodas;
    private javax.swing.JInternalFrame CitasMedicas;
    private javax.swing.JInternalFrame Cumpleanios;
    private javax.swing.JInternalFrame Otros;
    private javax.swing.JInternalFrame Reuniones;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JPanel eventosBodas;
    private javax.swing.JPanel eventosCitas;
    private javax.swing.JPanel eventosCumple;
    private javax.swing.JPanel eventosOtros;
    private javax.swing.JPanel eventosReuniones;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {

        //se obtiene el comando ejecutado
        String comando = e.getActionCommand();
        //se recorre el MAP
        Iterator it = componentes.entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry entry = (Map.Entry)it.next();
            //se obtiene el KEY -> identificador unico
            String itm = entry.getKey().toString();
            //si comando de componente es igual a comando pulsado
            if( itm.equals(comando))
            {
                //se recupera el contenido del JTextfield
                //String name = ((jpComponente) entry.getValue()).txtName.getText();
                //mostramos resultado
                //JOptionPane.showMessageDialog(null, "Se presiono boton " + itm + " \n Hola " );//+ name);
                
                detalle = new DetalleEvento(null, true, comando);
                detalle.setLocationRelativeTo(null);
                detalle.setVisible(true);
                
            }
        }

    }
}
