/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import net.sf.jcarrierpigeon.Notification;
import net.sf.jcarrierpigeon.NotificationQueue;
import net.sf.jcarrierpigeon.WindowPosition;

/**
 *
 * @author c3rberuss
 */
public class Notificacion extends javax.swing.JFrame {

    /**
     * Creates new form Notificacion
     */
    public Notificacion(int posicionY, String tipo, String Titulo, String texto) {
        initComponents();
        
        this.Texto.setText(texto);
        this.Titulo.setText(Titulo);
        
        Border border = BorderFactory.createEmptyBorder(0, 0, 0, 0);
        
        this.Texto.setBorder(border);
        this.Texto.repaint();
        setIcon(tipo);
        
        Notification obj = new Notification(this, WindowPosition.BOTTOMRIGHT, 5, posicionY, 5000);
        
        NotificationQueue vent = new NotificationQueue();
        vent.add(obj);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        Texto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setOpacity(0.7F);
        setPreferredSize(new java.awt.Dimension(400, 100));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onClick(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Notificacion.this.mouseExited(evt);
            }
        });

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setForeground(new java.awt.Color(255, 255, 255));

        Titulo.setText("Titulo");

        icono.setText("Icono");
        icono.setPreferredSize(new java.awt.Dimension(32, 32));
        icono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                click(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exited(evt);
            }
        });

        Texto.setEditable(false);
        Texto.setBackground(new java.awt.Color(255, 255, 255));
        Texto.setColumns(20);
        Texto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Texto.setForeground(new java.awt.Color(0, 0, 0));
        Texto.setLineWrap(true);
        Texto.setRows(5);
        Texto.setWrapStyleWord(true);
        Texto.setAutoscrolls(false);
        Texto.setBorder(null);
        Texto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                click(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exited(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(Titulo))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(icono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(Texto, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addGap(15, 15, 15)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Texto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mouseHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseHover
        this.setOpacity(1.0f);
    }//GEN-LAST:event_mouseHover

    private void mouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExited
        this.setOpacity(0.7f);
    }//GEN-LAST:event_mouseExited

    private void onClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onClick
        this.dispose();
    }//GEN-LAST:event_onClick

    private void hover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover
        mouseHover(evt);
    }//GEN-LAST:event_hover

    private void exited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exited
        mouseExited(evt);
    }//GEN-LAST:event_exited

    private void click(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_click
        onClick(evt);
    }//GEN-LAST:event_click

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notificacion(5, "info", "Notificion", "texto notificacion").setVisible(true);
            }
        });
    }

    private void setIcon(String tipo){
        
        ImageIcon icono;
        
        switch(tipo.toLowerCase()){
            case "cumpleaños":
                icono = new ImageIcon(getClass().getResource("/recursos/imagenes/cumpleanos.png"));
                this.icono.setIcon(icono);
                break;
            
            case "citas médicas":
                icono = new ImageIcon(getClass().getResource("/recursos/imagenes/citaMedica.png"));
                this.icono.setIcon(icono);
                
            case "reuniones":
                icono = new ImageIcon(getClass().getResource("/recursos/imagenes/ReunionesPestanha.png"));
                this.icono.setIcon(icono);
                break;
            case "otros":
                icono = new ImageIcon(getClass().getResource("/recursos/imagenes/evento.png"));
                this.icono.setIcon(icono);
                break;
            case "boda":
                icono = new ImageIcon(getClass().getResource("/recursos/imagenes/boda.png"));
                this.icono.setIcon(icono);
                break;
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Texto;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel icono;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
