/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author edwin
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
         Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/recursos/imagenes/iconoAgenda.png"));
        setIconImage(icon);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PanelCambiable = new javax.swing.JPanel();
        BtnTemporizador = new javax.swing.JButton();
        BtnCalendario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnApuntes = new javax.swing.JButton();
        BtnEventos = new javax.swing.JButton();
        BtnPerfil = new javax.swing.JButton();
        BtnCronometro = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("La agenda");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/agendaSuper.png"))); // NOI18N
        jLabel1.setText("LA AGENDA   ");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("00 DEL MES DEL 2017");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("00:00 A.M");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(851, 851, 851)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelCambiable.setBackground(new java.awt.Color(12, 12, 22));

        BtnTemporizador.setBackground(new java.awt.Color(0, 0, 0));
        BtnTemporizador.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        BtnTemporizador.setForeground(new java.awt.Color(255, 255, 255));
        BtnTemporizador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/tempo.png"))); // NOI18N
        BtnTemporizador.setText("MI TEMPORIZADOR");
        BtnTemporizador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BtnTemporizador.setBorderPainted(false);
        BtnTemporizador.setContentAreaFilled(false);
        BtnTemporizador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnTemporizador.setFocusPainted(false);
        BtnTemporizador.setIconTextGap(10);
        BtnTemporizador.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/tempoPeque.png"))); // NOI18N
        BtnTemporizador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnTemporizadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnTemporizadorMouseExited(evt);
            }
        });
        BtnTemporizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTemporizadorActionPerformed(evt);
            }
        });

        BtnCalendario.setBackground(new java.awt.Color(0, 0, 0));
        BtnCalendario.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        BtnCalendario.setForeground(new java.awt.Color(255, 255, 255));
        BtnCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/calendario.png"))); // NOI18N
        BtnCalendario.setText("MI CALENDARIO");
        BtnCalendario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BtnCalendario.setBorderPainted(false);
        BtnCalendario.setContentAreaFilled(false);
        BtnCalendario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCalendario.setFocusPainted(false);
        BtnCalendario.setIconTextGap(10);
        BtnCalendario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/calendarioPeque.png"))); // NOI18N
        BtnCalendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnCalendarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCalendarioMouseExited(evt);
            }
        });
        BtnCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalendarioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><center>BIENVENIDO A \"LA AGENDA\"<br> ¿QUE NECESITAS USAR HOY?</center></html>");

        BtnApuntes.setBackground(new java.awt.Color(0, 0, 0));
        BtnApuntes.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        BtnApuntes.setForeground(new java.awt.Color(255, 255, 255));
        BtnApuntes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/apuntes.png"))); // NOI18N
        BtnApuntes.setText("MIS APUNTES");
        BtnApuntes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BtnApuntes.setBorderPainted(false);
        BtnApuntes.setContentAreaFilled(false);
        BtnApuntes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnApuntes.setFocusPainted(false);
        BtnApuntes.setIconTextGap(10);
        BtnApuntes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/apuntesPeque.png"))); // NOI18N
        BtnApuntes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnApuntesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnApuntesMouseExited(evt);
            }
        });

        BtnEventos.setBackground(new java.awt.Color(0, 0, 0));
        BtnEventos.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        BtnEventos.setForeground(new java.awt.Color(255, 255, 255));
        BtnEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/eventoLogo.png"))); // NOI18N
        BtnEventos.setText("MIS EVENTOS");
        BtnEventos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BtnEventos.setBorderPainted(false);
        BtnEventos.setContentAreaFilled(false);
        BtnEventos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEventos.setFocusPainted(false);
        BtnEventos.setIconTextGap(10);
        BtnEventos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/eventoLogoPeque.png"))); // NOI18N
        BtnEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnEventosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnEventosMouseExited(evt);
            }
        });
        BtnEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEventosActionPerformed(evt);
            }
        });

        BtnPerfil.setBackground(new java.awt.Color(0, 0, 0));
        BtnPerfil.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        BtnPerfil.setForeground(new java.awt.Color(255, 255, 255));
        BtnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/perfil.png"))); // NOI18N
        BtnPerfil.setText("MI PERFIL");
        BtnPerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BtnPerfil.setBorderPainted(false);
        BtnPerfil.setContentAreaFilled(false);
        BtnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnPerfil.setFocusPainted(false);
        BtnPerfil.setIconTextGap(30);
        BtnPerfil.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/perfilPeq.png"))); // NOI18N
        BtnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnPerfilMouseExited(evt);
            }
        });

        BtnCronometro.setBackground(new java.awt.Color(0, 0, 0));
        BtnCronometro.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        BtnCronometro.setForeground(new java.awt.Color(255, 255, 255));
        BtnCronometro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/cro.png"))); // NOI18N
        BtnCronometro.setText("MI CRONOMETRO");
        BtnCronometro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BtnCronometro.setBorderPainted(false);
        BtnCronometro.setContentAreaFilled(false);
        BtnCronometro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCronometro.setFocusPainted(false);
        BtnCronometro.setIconTextGap(10);
        BtnCronometro.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/croPeq.png"))); // NOI18N
        BtnCronometro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnCronometroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCronometroMouseExited(evt);
            }
        });
        BtnCronometro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCronometroActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelCambiableLayout = new javax.swing.GroupLayout(PanelCambiable);
        PanelCambiable.setLayout(PanelCambiableLayout);
        PanelCambiableLayout.setHorizontalGroup(
            PanelCambiableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCambiableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(PanelCambiableLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(PanelCambiableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(PanelCambiableLayout.createSequentialGroup()
                        .addGroup(PanelCambiableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnEventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnCronometro, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))
                        .addGap(77, 77, 77)
                        .addGroup(PanelCambiableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnApuntes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnCalendario, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
                        .addGap(74, 74, 74)
                        .addGroup(PanelCambiableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnTemporizador, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))))
                .addGap(37, 37, 37))
        );
        PanelCambiableLayout.setVerticalGroup(
            PanelCambiableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCambiableLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCambiableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnTemporizador, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(PanelCambiableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnApuntes, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("[LA AGENDA] | COPYRIGHTS ® 2017");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelCambiable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelCambiable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTemporizadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnTemporizadorMouseEntered
        this.BtnTemporizador.setBorderPainted(true);
    }//GEN-LAST:event_BtnTemporizadorMouseEntered

    private void BtnTemporizadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnTemporizadorMouseExited
        this.BtnTemporizador.setBorderPainted(false);
    }//GEN-LAST:event_BtnTemporizadorMouseExited

    private void BtnCalendarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCalendarioMouseEntered
        this.BtnCalendario.setBorderPainted(true);
    }//GEN-LAST:event_BtnCalendarioMouseEntered

    private void BtnCalendarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCalendarioMouseExited
        this.BtnCalendario.setBorderPainted(false);
    }//GEN-LAST:event_BtnCalendarioMouseExited

    private void BtnApuntesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnApuntesMouseEntered
        this.BtnApuntes.setBorderPainted(true);
    }//GEN-LAST:event_BtnApuntesMouseEntered

    private void BtnApuntesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnApuntesMouseExited
        this.BtnApuntes.setBorderPainted(false);
    }//GEN-LAST:event_BtnApuntesMouseExited

    private void BtnEventosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEventosMouseEntered
        this.BtnEventos.setBorderPainted(true);
    }//GEN-LAST:event_BtnEventosMouseEntered

    private void BtnEventosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEventosMouseExited
        this.BtnEventos.setBorderPainted(false);
    }//GEN-LAST:event_BtnEventosMouseExited

    private void BtnPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPerfilMouseEntered
        this.BtnPerfil.setBorderPainted(true);
    }//GEN-LAST:event_BtnPerfilMouseEntered

    private void BtnPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPerfilMouseExited
        this.BtnPerfil.setBorderPainted(false);
    }//GEN-LAST:event_BtnPerfilMouseExited

    private void BtnCronometroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCronometroMouseEntered
        this.BtnCronometro.setBorderPainted(true);
    }//GEN-LAST:event_BtnCronometroMouseEntered

    private void BtnCronometroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCronometroMouseExited
        this.BtnCronometro.setBorderPainted(false);
    }//GEN-LAST:event_BtnCronometroMouseExited

    private void BtnCronometroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCronometroActionPerformed
        Crono cr = new Crono(this,true);
        cr.setVisible(true);
        
    }//GEN-LAST:event_BtnCronometroActionPerformed

    private void BtnCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalendarioActionPerformed
        Calendario cal = new Calendario(this,true);
        cal.setVisible(true);
    }//GEN-LAST:event_BtnCalendarioActionPerformed

    private void BtnTemporizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTemporizadorActionPerformed
        Temporizador tem = new Temporizador(this,true);
        tem.setVisible(true);
    }//GEN-LAST:event_BtnTemporizadorActionPerformed

    private void BtnEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEventosActionPerformed
        OpcionesEventos eve = new OpcionesEventos(new javax.swing.JDialog(),true);
        eve.setVisible(true);
    }//GEN-LAST:event_BtnEventosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnApuntes;
    private javax.swing.JButton BtnCalendario;
    private javax.swing.JButton BtnCronometro;
    private javax.swing.JButton BtnEventos;
    private javax.swing.JButton BtnPerfil;
    private javax.swing.JButton BtnTemporizador;
    private javax.swing.JPanel PanelCambiable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
