/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;


/**
 *
 * @author c3rberuss
 */
public class TarjetaEvento extends javax.swing.JPanel {

    /**
     * Creates new form tarjeta_Eventos
     */
    
    private URL url;
    private Image image;
    
    public TarjetaEvento(String mes) {
        initComponents();
        url = getClass().getResource("/recursos/imagenes/meses/"+mes.toLowerCase()+".jpg");
        
        image  = new ImageIcon(url).getImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ver = new javax.swing.JButton();
        Fecha = new javax.swing.JLabel();
        Mes = new javax.swing.JLabel();
        titulo = new javax.swing.JTextArea();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(420, 100));
        setPreferredSize(new java.awt.Dimension(420, 130));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/view.png"))); // NOI18N
        Ver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Ver.setBorderPainted(false);
        Ver.setContentAreaFilled(false);
        Ver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ver.setFocusPainted(false);
        Ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VerMouseExited(evt);
            }
        });
        add(Ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 47, 26));
        Ver.getAccessibleContext().setAccessibleDescription("");

        Fecha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Fecha.setForeground(new java.awt.Color(0, 0, 0));
        Fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fecha.setText("Miercoles 15");
        add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 120, 24));

        Mes.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        Mes.setForeground(new java.awt.Color(0, 0, 0));
        Mes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mes.setText("DIC");
        add(Mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 120, 61));

        titulo.setEditable(false);
        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setColumns(20);
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setLineWrap(true);
        titulo.setRows(5);
        titulo.setWrapStyleWord(true);
        titulo.setBorder(null);
        add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 250, 33));
    }// </editor-fold>//GEN-END:initComponents

    private void VerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerMouseEntered
        this.Ver.setBorderPainted(true);
    }//GEN-LAST:event_VerMouseEntered

    private void VerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerMouseExited
        this.Ver.setBorderPainted(false);
    }//GEN-LAST:event_VerMouseExited


 
    @Override
    public void paint(Graphics g){
        g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
        this.setOpaque(false);
        super.paint(g);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Fecha;
    public javax.swing.JLabel Mes;
    public javax.swing.JButton Ver;
    public javax.swing.JTextArea titulo;
    // End of variables declaration//GEN-END:variables
}
