/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;


/**
 *
 * @author c3rberuss
 */
public class TarjetaEvento extends javax.swing.JPanel {

    /**
     * Creates new form tarjeta_Eventos
     */
    public TarjetaEvento() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ver = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        Mes = new javax.swing.JLabel();

        setBorder(new org.edisoncor.gui.util.DropShadowBorder());
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(420, 100));
        setPreferredSize(new java.awt.Dimension(420, 100));

        Ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/view.png"))); // NOI18N
        Ver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Ver.setBorderPainted(false);
        Ver.setContentAreaFilled(false);
        Ver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ver.setFocusPainted(false);
        Ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VerMouseExited(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Titulo del Evento");

        Fecha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Fecha.setForeground(new java.awt.Color(0, 0, 0));
        Fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fecha.setText("Miercoles 15");

        Mes.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        Mes.setForeground(new java.awt.Color(0, 0, 0));
        Mes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mes.setText("DIC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Mes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Ver, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Mes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Ver, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Ver.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void VerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerMouseEntered
        this.Ver.setBorderPainted(true);
    }//GEN-LAST:event_VerMouseEntered

    private void VerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerMouseExited
        this.Ver.setBorderPainted(false);
    }//GEN-LAST:event_VerMouseExited

    private URL url = getClass().getResource("/recursos/imagenes/tarjeta.jpg");
    Image image = new ImageIcon(url).getImage();
 
    @Override
    public void paint(Graphics g){
        g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
        this.setOpaque(false);
        super.paint(g);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Fecha;
    public javax.swing.JLabel Mes;
    public javax.swing.JButton Ver;
    public javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
